version: "2"

services: 
  mongodb:
    build: .
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      #- MONGODB_USER="admin" 
      #- MONGODB_PASS="admin"
    volumes:
      - $PWD/data/db:/data/db
      #- $PWD/mongodb.conf:/etc/mongodb.conf

    ports:
      - 27018:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

